### ISSUE TITLE
Game crashes (closes) when you try to play with 2 players

### ISSUE THREAD

**Issue by SupraGL** [MidflightDigital/XX--STARLiGHT--twopointzero#24] opened 2022-04-22 12:56 UTC
**Describe the bug**
When you join 2 players with the log-in page, the game crashes right before loading the song list.
It works fine with the Soundwaves theme. It works fine if you add a second player in the song selection.

**To Reproduce**
1. Open the game.
2. Select 'Game Mode'.
3. Enter player 1 and player 2.
4. Select 'Versus Mode'.
5. Get through the 'Caution' window.
6. The game will crash after.

**Expected behavior**
When you join 2 players with the log-in page, the game should load to the song selection with both players without crashing.

**Screenshots**
No screenshot applicable.

**Desktop (please complete the following information):**
 - OS: Windows 7 (also tested with Windows 11)
 - StepMania/Outfox Version: 0.4.14.1
 - Theme Version: 2.1.0HF

**Additional context**
[info.txt](https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/files/8541108/info.txt)
[log.txt](https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/files/8541109/log.txt)

**Comment by trulow** [comment] 2022-04-28 05:12
I'm having the same issue as well. I thought it was Outfox at first but then I disabled the starlight theme and 2 player versus works as intended.

**Comment by Inorizushi** [comment] 2022-04-29 05:40
I personally don't know what's causing the issue, I'll continue looking for why this is happening. It's definitely something to do with loading two profiles though

**Comment by Inorizushi** [comment] 2022-04-29 06:13
I just tested against Outfox 4.12.0 and the game doesn't crash, I'll check what changes were made between that version and 4.14

**Comment by Inorizushi** [comment] 2022-05-25 19:34
Fixed on the repo https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/2e1bab5e2a40d30ab2db56ead8cdf9c8031fe756

**Closed** 2024-02-21 11:02 UTC
Labels: bug, Game Breaking, Fixed on Repository
